# Generated by Django 5.0.3 on 2024-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offer or discount on the product', max_digits=10, null=True),
        ),
    ]
