# Generated by Django 5.0.3 on 2024-05-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaResponseBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.mpesaresponsebody'),
        ),
    ]
