# Generated by Django 5.0.3 on 2024-05-20 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_mpesaresponsebody_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='country_name',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(default='070000000', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='second_name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter keywords separated by commas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='grocery.category'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grocery.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='grocery.subcategory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocery.order')),
            ],
        ),
    ]
