# Generated by Django 5.0.3 on 2024-05-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_category_remove_delivery_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='tip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.tip'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
